update so script will not crash if no metainfo is present
ucgmsim/visualization pull request #61
Opened 2021-02-23 20:38 UTC by shot0829

2021-02-23 20:51 UTC, jasonmotha requested changes

2021-02-23 20:51 UTC, jasonmotha commented on visualization/im_plotting/im_plot.py
> +        return "",None
Add a comment saying what this is doing. Or add it to the function docstring.

2021-02-23 21:19 UTC, jasonmotha approved these changes
Looks good. Test output says black is failing.

2021-02-26 02:26 UTC, sungeunbae approved these changes

2021-02-26 02:27 UTC, merged