Vmplot
ucgmsim/visualization pull request #62
Opened 2021-03-31 02:00 UTC by viktor76525

2021-03-31 02:52 UTC, jasonmotha reviewed
I think it would be good for people in the future modifying / using this script if there was a little more structure. Perhaps a main function instead of most things being in the global space. 

I don't think the impact of this script is big but would be good to keep things that get merged into the repo in good stead.

2021-03-31 02:53 UTC, jpa198 approved these changes

2021-03-31 03:59 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +with open(os.path.join(args.vm_dir, "vm_params.yaml")) as y:
The VM dir is needed for the vs file too. The VM dir has a fixed structure. Is there any case where it would be different?

2021-03-31 04:05 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +with open(os.path.join(args.vm_dir, "vm_params.yaml")) as y:
Just noticed it isn't. In that case, may as well.

2021-03-31 22:58 UTC, jpa198 requested changes

2021-03-31 22:58 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +rmtree(gmt_temp)
This section should be in a `__name__=="__main__"` block

2021-03-31 22:58 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    os.makedirs(args.out_dir)
Using the exist_ok=True argument for makedirs removes the need for the if statement

2021-03-31 22:59 UTC, jasonmotha requested changes

2021-03-31 22:59 UTC, jasonmotha commented on visualization/gmt/plot_vm_depths.py
> +    depth_gs = "{}/{}_{}.ps".format(depth_wd, os.path.basename(args.vm_file).replace(".", "_"), depth)
I generally prefer f-strings over format. It's easier to see where each variable is used in the string.

2021-03-31 23:14 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +    depth_gs = "{}/{}_{}.ps".format(depth_wd, os.path.basename(args.vm_file).replace(".", "_"), depth)
I don't think it works for non-simple variables like os.path.basename(args.vm_file).replace(".", "_")
unless another variable is made just so that the f string can be used which seems to defeat the purpose?

2021-04-01 00:35 UTC, jasonmotha commented on visualization/gmt/plot_vm_depths.py
> +    depth_gs = "{}/{}_{}.ps".format(depth_wd, os.path.basename(args.vm_file).replace(".", "_"), depth)
The variable / function within the {} get's evaluated so it'll work for pretty much anything - you can even put a ternary in there.

2021-04-01 00:50 UTC, jasonmotha requested changes
There's another couple of entries with ".format" which would be good to switch over.

2021-04-01 01:23 UTC, sungeunbae reviewed
See below

2021-04-01 01:23 UTC, sungeunbae commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
@viktor76525  To my eyes, passing args around seems not ideal. Can we just pass relevant values only?

2021-04-01 01:23 UTC, sungeunbae commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
Related to template_gs() and finish_gs()

2021-04-01 01:24 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
Yes, but 15 parameters would be too much. Alternatively a restructure, packaging related arguments into dictionaries can work. Seems like a lot of work for 300 lines though (with black making it have lots of whitespace).

2021-04-01 01:33 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
My only other suggestion would be to make a dataclass to hold the gmt parameters. That way we're not passing around a black box, but also don't way too many arguments.
Would be a bit too much infrastructure for a single script like this though

2021-04-01 01:35 UTC, jpa198 approved these changes

2021-04-01 01:35 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    gmt_temp = mkdtemp()
Could use `with TemporaryDirectory as gmt_temp:` instead of creating and cleaning up manually

2021-04-01 02:03 UTC, jasonmotha commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
Arguably a GMT dataclass could be used in any refactoring of GMT plots or any new plots that we end up writing.

2021-04-01 02:21 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
The way I see it, defaults would include unused variables which may be more confusing. Dictionaries like used in GMSimViz would be useful.

2021-04-01 02:31 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +        "--page-height", help="height of figure * dpi = pixels", type=float, default=9
I can do that next working day, even though pixels / dots per inch = inch.
I want to try something and there are 1.5 hours left today, I find context switching difficult and pr requests one at a time is a slow process.

2021-04-01 02:31 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    temp_object = TemporaryDirectory()
If you're not using TemporaryDirectory as a context manager you still need to clean it up after.
The old way was fine, I did approve it

2021-04-01 02:31 UTC, viktor76525 commented on visualization/gmt/plot_vm_depths.py
> +    temp_object = TemporaryDirectory()
Tested it, gets cleanup up on python exit.

2021-04-06 20:52 UTC, jasonmotha commented on visualization/gmt/plot_vm_depths.py
> +    gmt_temp = mkdtemp()
Does it still clean up the directory without the with if it crashes?

2021-04-06 22:01 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    gmt_temp = mkdtemp()
The documentation claims that all clean up is the users responsibility, so any automatic clean up is just a bonus

2021-04-12 23:11 UTC, sungeunbae commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
@viktor76525 Discovered that this PR has been on hold. I think a good compromise here is a dictionary - no major restructure and no passing of args.

2021-04-13 00:00 UTC, jpa198 commented on visualization/gmt/plot_vm_depths.py
> +    gs_file = template_gs(args, corners_gmt, map_width, map_height, gmt_temp)
I think this is fine for now, changing to a dictionary is just the same issue with a different haircut.
Can be refactored later if we ever get a GMT dataclass.

2021-04-13 23:09 UTC, sungeunbae approved these changes
I like how arguments are logically classified into 3 dictionaries and only relevant arguments are passed to functions.

2021-04-13 23:37 UTC, jpa198 approved these changes
Looks good, I'm on board with the way dictionaries have been used here. (As a stepping stone to dataclasses)

2021-04-13 23:43 UTC, jasonmotha approved these changes
Perfect! :smile:

2021-04-13 23:43 UTC, jpa198 commented
Now we just need the Jenkins server to be sorted out...

2021-04-14 03:16 UTC, merged