Clean
ucgmsim/visualization pull request #64
Opened 2021-05-19 21:26 UTC by viktor76525

updated structure
fixed stuff

2021-05-20 22:30 UTC, jpa198 requested changes

2021-05-20 23:42 UTC, jasonmotha requested changes

2021-05-20 23:42 UTC, jasonmotha commented on im/im_rrup_mean.py
> +            sys.exit("SRF Info file required if yaml config given.")
or raise ArgumentErrors for parsing issues.

2021-05-20 23:42 UTC, jasonmotha commented on im/im_rrup_mean.py
> +    parser.add_argument("--imlabel", help="label for each imcsv, eg: Obs or Sim")
Or perhaps could merge it with the above with an n-args=2. So that for every --imcsv you provide you also have to provide a label.

2021-05-20 23:42 UTC, jasonmotha commented on im/summarise_all_rels_im.py
> +        output_dir, fault_name + "_log_{}.csv".format(stat_fn.__name__)
Or update the whole thing to an f-string.

2021-05-21 01:57 UTC, viktor76525 commented on animation/plot_srf_animation.py
> +for plane in range(len(srf_bounds)):
On this one I don't see the point. Enumerate is when you want the number and the value. Here, only the number is used.
It would just create an extra unused variable.
for plane, _ in enumerate(srf_bounds):
?

2021-05-21 02:09 UTC, viktor76525 commented on im/plot_disagg.py
> +#!/usr/bin/env python
Doesn't this plot still get used? Seemed like a unique plot which would come in handy too.

2021-05-21 02:13 UTC, viktor76525 commented on im/psa_bias.py
> +    plt.ylabel(f"pSA residual, ln({args.imlabel[0]})-ln(GMM)", fontsize=14)
theyre all in the same plot so there is no i? just different series

2021-05-21 02:30 UTC, viktor76525 commented on im/summarise_all_rels_im.py
> +#!/usr/bin/env python
Not sure, @sungeunbae ?

2021-05-21 02:32 UTC, viktor76525 commented on prototype/plot_proximity.py
> +from visualization.config import data_path
The reason for this is that it knows where the python package is located and it's associated date. The other option is doing something funky with the setup script.

2021-05-21 02:53 UTC, jasonmotha commented on im/plot_disagg.py
> +#!/usr/bin/env python
Not this particular block of code. The json file isn't created in a workflow anymore to my knowledge.

Agree that it is a cool way of doing 3D column plots but we always can use this as a reference if need be.

2021-05-21 02:55 UTC, viktor76525 commented on im/plot_disagg.py
> +#!/usr/bin/env python
ok, I assume this has been duplicated with different inputs in seistech

2021-05-21 02:57 UTC, jasonmotha commented on im/plot_disagg.py
> +#!/usr/bin/env python
Yep - every other 3D plotting library had issues with z-indexing.
 I've forwarded the changes you made here to Claudio too in case he wanted to implement it .

2021-05-21 03:19 UTC, jasonmotha commented on im/im_rrup_mean.py
> +    parser.add_argument(
I think there are a few more instances of this in the PR.

2021-05-21 03:20 UTC, viktor76525 commented on im/im_rrup_mean.py
> +    parser.add_argument(
nargs=2 or have labels optional? I haven't been running this, don't think i will be directly so which one?

2021-05-21 03:46 UTC, jasonmotha commented on im/im_rrup_mean.py
> +    parser.add_argument(
The imlabel expecting a list. I think there were 3 or 4 argparse files that needed them.

2021-05-21 03:47 UTC, jpa198 commented on im/im_rrup_mean.py
> +    parser.add_argument(
The imcsv, imlabel arguments could be abstracted out into a function that adds them, so we don't need 4 copies of the same arguments spread out through the repo

2021-05-21 03:48 UTC, viktor76525 commented on im/im_rrup_mean.py
> +    parser.add_argument(
yes, but do we want to keep them as separate or non-optional nargs=2 for imcsv param containing label.

2021-05-21 03:48 UTC, jpa198 commented on im/im_rrup_mean.py
> +    parser.add_argument(
I think nargs=2 will be safer, easier to find an argument without both bits

2021-05-21 03:58 UTC, sungeunbae commented on im/summarise_all_rels_im.py
> +#!/usr/bin/env python
True - I think this accidentally crept in?

2021-05-21 03:58 UTC, sungeunbae commented on waveform/waveforms_sim_obs.py
> +            for i in range(len(extensions))
Merge and call it compare_waveforms.py?

2021-05-21 04:01 UTC, jasonmotha commented on im/im_rrup_mean.py
> +    parser.add_argument(
Agreed. Most of the options are splitting hairs though. nargs=2 seems better to me because you can keep the data next to the label for easy reference.

2021-05-21 04:01 UTC, jpa198 commented on waveform/waveforms_sim_obs.py
> +            for i in range(len(extensions))
The arguments can use a similar format as the --imcsv --imlabel system, with nargs=3 for the format (ascii/binary)

2021-05-21 05:00 UTC, jasonmotha commented on waveform/waveforms_sim_obs.py
> +from qcore.timeseries import BBSeis, LFSeis, HFSeis
As a note, at this stage we'd use BB or ascii to read the waveforms. Support for HF/LF isn't needed as such.

2021-05-21 05:14 UTC, jpa198 commented on waveform/waveforms_sim_obs.py
> +from qcore.timeseries import BBSeis, LFSeis, HFSeis
I'd like to lobby for HF/LF support. The way I did it in sim_sim should mean it just uses a look up dict to match letter to Seis type, and it works as expected from there

2021-05-27 03:29 UTC, viktor76525 commented on im/psa_bias.py
> +    assert len(args.imcsv) > 1
nope

2021-05-27 03:31 UTC, viktor76525 commented on im/psa_comparisons.py
> +        psas.append(
seems a bit trivial, IM names from columns?

2021-05-27 03:32 UTC, viktor76525 commented on im/psa_comparisons.py
> +    args = parser.parse_args()
done

2021-05-27 03:33 UTC, jasonmotha commented on im/psa_bias.py
> +    assert len(args.imcsv) > 1
I thought you'd get an index out of range error if you ran out of colours?

2021-05-27 03:43 UTC, jasonmotha commented on im/psa_comparisons.py
> +    exit()
These lines look like they're a hangover from testing?

2021-05-27 03:45 UTC, viktor76525 commented on im/psa_bias.py
> +    assert len(args.imcsv) > 1
% len(colours) :p

2021-05-27 03:46 UTC, viktor76525 commented on im/psa_comparisons.py
> +    exit()
hmm

2021-05-27 03:48 UTC, jasonmotha commented on im/psa_bias.py
> +    plt.ylabel(f"pSA residual, ln({args.imlabel[0]})-ln(GMM)", fontsize=14)
Oh yep. That makes sense.

2021-05-27 03:49 UTC, jasonmotha commented on im/psa_comparisons.py
> +        psas.append(
Yeah. Loading im files and then the filtering of pSA / sigma. It's okay as is if you want to leave it.

2021-05-27 03:53 UTC, viktor76525 commented on im/psa_comparisons.py
> +        psas.append(
maybe a param in load_im_file_pd? but this pr is huge, I would try to avoid it rn

2021-05-27 03:54 UTC, jasonmotha commented on im/psa_comparisons.py
> +        psas.append(
Sweet. Sounds good.

2021-05-28 00:17 UTC, jpa198 requested changes
Some of the things I've noted are wishlist rather than requirements

2021-05-28 00:17 UTC, jpa198 commented on waveform/waveforms.py
> +        default=-1,
Default None would be better here, then plot for either n_stations or all stations?

2021-05-28 00:17 UTC, jpa198 commented on waveform/waveforms.py
> +        parser.error("Duration -t / --tmax must be greater than 0")
Should also validate that n_stations is greater than 0, unless it's the all option

2021-05-28 00:17 UTC, jpa198 commented on waveform/waveforms.py
> +    p.starmap(plot_station, msgs)
Using a partial function here would be tidier, and have less copies of the same data lying around. Not a big problem though

2021-05-28 00:17 UTC, jpa198 commented on waveform/waveforms.py
> +        stations_all = np.intersect1d(stations_all, stats)
I think there's already been a comment in another location. 
Between station lists and intensity measures this functionality seems to get used a lot, so it should be turned into a function and abstracted out?

2021-05-28 00:17 UTC, jpa198 commented on waveform/waveforms.py
> +    args = parser.parse_args()
An argument to list specific stations to plot would be nice, but not necessary.

2021-05-28 04:12 UTC, viktor76525 commented on waveform/waveforms.py
> +    """
I think anything that can be automated should be. Any automatic format checker would basically be following the same logic as is the case here.

2021-05-28 04:14 UTC, viktor76525 commented on waveform/waveforms.py
> +    """
I've added automatically detected, yes, logic has 4 outcomes, a choice between 2 followed by another choice between 2.

2021-05-28 04:20 UTC, viktor76525 commented on waveform/waveforms.py
> +    args = parser.parse_args()
It's the case in another script. But it's hard to work with nice to have, should either be yes or no. Not even sure how these scripts are  being used personally.

2021-05-30 22:51 UTC, jpa198 commented on waveform/waveforms.py
> +    args = parser.parse_args()
Giving a specific station is usually used when something odd has happened to that station during a simulation and we want to check the waveform. Giving the waveform just saves generating and digging through all the station plots.

2021-05-30 23:08 UTC, jpa198 approved these changes

2021-05-31 02:23 UTC, jasonmotha requested changes
Looking good overall. Just a couple of minor things that need commenting on.

2021-05-31 03:39 UTC, jpa198 commented on visualization/config.py
> +data_path = os.path.join(os.path.dirname(__file__), "data")
This could use package_data in setup.py, and then access it with pkg_resources?
https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

2021-05-31 03:41 UTC, jpa198 commented on visualization/config.py
> +data_path = os.path.join(os.path.dirname(__file__), "data")
Loading it etc can still be abstracted out into a util script, so the path just needs to be imported?

2021-06-01 06:03 UTC, viktor76525 commented on visualization/config.py
> +data_path = os.path.join(os.path.dirname(__file__), "data")
before you ask:
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access
> Note that resource names must be /-separated paths rooted at the package, cannot contain relative names like "..", and cannot be absolute. Do not use os.path routines to manipulate resource paths, as they are not filesystem paths.

2021-06-01 22:28 UTC, jasonmotha approved these changes

2021-06-01 22:29 UTC, jasonmotha commented
Happy as! Cheers!

2021-06-02 00:02 UTC, merged