Orchestrate various plotting to compare two runs
ucgmsim/visualization pull request #67
Opened 2021-07-16 03:25 UTC by sungeunbae

2021-07-16 04:30 UTC, viktor76525 commented on im/psa_bias.py
> +from pathlib import Path
doesn't seem to be used

2021-07-16 04:36 UTC, viktor76525 commented on im/psa_ratios_rrup.py
> +        "stats", help="ll or rrup file for locations", type=os.path.abspath
This was meant to be type=Path and below too?

2021-07-16 04:41 UTC, viktor76525 commented on visualization/plot_items_wrapper.py
> +    skiprows = 1 if header_exists is True else 0
skiprows = 1 if header_exists else 0

2021-07-16 05:34 UTC, jasonmotha commented
Haven't reviewed this, I may have comments when I get back. But if urgent don't wait on me to merge it in.

2021-07-19 03:42 UTC, sungeunbae commented on visualization/plot_items_wrapper.py
> +    skiprows = 1 if header_exists is True else 0
Sure

2021-07-19 04:14 UTC, sungeunbae commented on im/psa_bias.py
> +from pathlib import Path
Used now

2021-07-19 04:15 UTC, sungeunbae commented on im/psa_ratios_rrup.py
> +        "stats", help="ll or rrup file for locations", type=os.path.abspath
Yes. Thanks

2021-07-20 00:12 UTC, jpa198 approved these changes
Looks good. All the scripts have been tested?

2021-07-20 00:12 UTC, jpa198 commented on compare/compare_runs.py
> +    parser.add_argument("--diff_ani", action="store_true", default=False)
Could add an extra --all argument to generate all the plots

2021-07-20 03:17 UTC, viktor76525 approved these changes

2021-07-20 03:19 UTC, sungeunbae commented on im/im_ratios.py
> +def ratios_to_csv(imcsv1, imcsv2, output_path: Path, comp=None, summary=False):
Addressed in the next commit

2021-07-20 03:26 UTC, sungeunbae commented on im/psa_ratios_rrup.py
> +        action="append",
Addressed in the next commit. 

> help="path to IM file and label. if more than one is supplied, will be compared to first one",

2021-07-20 04:46 UTC, sungeunbae commented on sources/plot_items.py
> +    pool = Pool(args.nproc)
Addressed in the next commit

2021-07-20 04:59 UTC, sungeunbae commented on compare/compare_runs.py
> +        help="Only used for difference animation",
I realised most jobs are in fact serial jobs, except for plot_items and diff_ani. Fixed the help and also re-classified the jobs.

2021-07-20 04:59 UTC, sungeunbae commented on compare/compare_runs.py
> +    parser.add_argument("--diff_ani", action="store_true", default=False)
Good idea

2021-07-20 21:04 UTC, jpa198 requested changes
Just going over the recent changes now

2021-07-20 23:33 UTC, jpa198 requested changes

2021-07-22 01:21 UTC, sungeunbae commented on im/im_rrup_mean.py
> +        help="path to IM file and label. if more than one is supplied, will be compared to first one",
Well spotted.

2021-07-22 01:21 UTC, sungeunbae commented on sources/plot_items.py
> +    with TemporaryDirectory() as gmt_temp:
Yes, tested.

2021-07-22 01:46 UTC, sungeunbae commented on compare/compare_runs.py
> +def run_all(parallel_jobs, serial_jobs, func_jobs, n_procs=1):
Ah, now I understand why that part of the code looked odd. Fixed.

2021-07-22 01:54 UTC, jpa198 approved these changes
Cool, looks good

2021-07-22 05:00 UTC, sungeunbae commented
> Cool, looks good
Hooray! Thank you my loyal reviewers

2021-07-22 05:00 UTC, merged

2021-07-28 04:11 UTC, jasonmotha reviewed
Looks really good. Just a few off-hand comments / thoughts. Nothing needs to change =)

@sungeunbae @jpa198

2021-07-28 04:11 UTC, jasonmotha commented on compare/compare_runs.py
> +    parser.add_argument("--git_base", type=Path, default="$gmsim")
Since we are only calling visualisation scripts here, we could have done everything as a relative path based from this script?
Otherwise, passing the path to the visualisation folder seems more appropriate?

2021-07-28 04:11 UTC, jasonmotha commented on compare/compare_runs.py
> +            git_base / "Empirical_Engine" / "empirical" / "util" / "model_config.yaml"
Would actually recommend --config being passed as none so it uses the default in empirical engine.

2021-07-28 05:02 UTC, sungeunbae commented on im/im_rrup_mean.py
> +    im_name = IM.from_im_name(im).get_im_name().replace(".", "p")
Fair point, in fact I wondered if there was a function that does something similar

2021-07-28 05:03 UTC, sungeunbae commented on compare/compare_runs.py
> +    parser.add_argument("--git_base", type=Path, default="$gmsim")
Well, it also wants to use Empirical_Engine...

2021-07-28 05:14 UTC, sungeunbae commented on compare/compare_runs.py
> +            git_base / "Empirical_Engine" / "empirical" / "util" / "model_config.yaml"
Trying to understand what you mean here. Are you suggesting if --config is not specified, and if --srf is not None, im_rrup_mean.py should use  `git_base / "Empirical_Engine" / "empirical" / "util" / "model_config.yaml"` as the default config? If I understand it correctly, yeah, I like the idea.

2021-07-28 05:28 UTC, jasonmotha commented on compare/compare_runs.py
> +            git_base / "Empirical_Engine" / "empirical" / "util" / "model_config.yaml"
It's probably poorly documented but it should work correctly if --config isn't set when calling im_rrup_mean