CS 21p6 plotting scenarios
ucgmsim/visualization pull request #74
Opened 2021-09-10 02:19 UTC by joelridden

### **Adding Cybershake scenario plotting scripts**

- Added 4 scripts for getting data and plotting
- Added readme to understand file structure and how to use scripts
- Added yaml files for configs

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_data.py
> +import os
Can I get you to add a description for each script at the top, just roughly what it does.
Could also pass this to the ArgumentParser, and then it gets printed when --help is used (I think)

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_data.py
> +        os.system(
I think we generally use subprocess.run? @jasonmotha?

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_data.py
> +        help="Full file path to the summarise_all_rels_im script",
Maybe add that its a script from IM_calculation?

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_epsilon.py
> +
blank line

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_epsilon.py
> +
No need for a blank line here, as `epsilon` is populated in the for block, so should therefore sit with it?

2021-09-13 00:45 UTC, claudio525 commented on cybershake/scenario_im_fault.py
> +
blank line

2021-09-13 01:48 UTC, jasonmotha commented on cybershake/scenario_data.py
> +        os.system(
Yeah a mix between subprocess - call, run and popen. Either way subprocess would be a better call.

2021-09-13 02:39 UTC, jpa198 reviewed
Mostly minor things, but each one repeated in multiple places

2021-09-13 02:39 UTC, jpa198 commented on cybershake/scenario_epsilon.py
> +                spatialise_im_ffp = Path(visualization_ffp) / "im/spatialise_im.py"
"im" / "spatialise_im.py"
Don't need to cast to Path either, the typing indicates it should be a Path object already

2021-09-13 02:39 UTC, jpa198 commented on cybershake/scenario_epsilon.py
> +                pd.DataFrame.to_csv(im_df, fault_im_filename, index=False)
You should be able to call im_df.to_csv(fault_im_filename, index=False)
NBD though

2021-09-13 02:39 UTC, jpa198 commented on cybershake/scenario_data.py
> +        os.system(
The qcore.shared functions for calling external commands use subprocess.popen

2021-09-13 05:37 UTC, jpa198 commented on cybershake/scenario_data.py
> +        subprocess.Popen(shlex.split(f"{summarise_im_ffp} {im_csv_dir} {fault} --im {' '.join(ims)} --output {output_dir}"))
@shot0829 would shlex.split help with any of the kisti -V issues you've been having?

2021-09-13 05:37 UTC, jpa198 commented on cybershake/scenario_epsilon.py
> +                spatialise_im_ffp = visualization_ffp / "im/spatialise_im.py"
Split the string too

2021-09-13 05:37 UTC, jpa198 commented on cybershake/scenario_im_fault.py
> +                        f"/{plot_items_ffp} {plot_options} --xyz {non_uniform_im} -f {plot_output_filename} --xyz-cpt-labels {plot_output_filename} -c '{config['srfs'][fault]}' --outline-fault-colour
Is the leading / in the string supposed to be there?

2021-09-13 05:37 UTC, jpa198 commented on cybershake/scenario_data.py
>      parser = argparse.ArgumentParser()
You should add the script doc string to ArgParser with ```desc="<string content>"```

2021-09-13 06:11 UTC, shot0829 commented on cybershake/scenario_data.py
> +        subprocess.Popen(shlex.split(f"{summarise_im_ffp} {im_csv_dir} {fault} --im {' '.join(ims)} --output {output_dir}"))
sadly no, shlex is just a smarter string.split() .
and the issue was pbs have some weird syntax rules for certain options/arguments.

2021-09-13 22:13 UTC, jpa198 commented on cybershake/scenario_data.py
>      parser = argparse.ArgumentParser()
Good catch on it actually being description=""

2021-09-13 22:19 UTC, jpa198 approved these changes

2021-09-13 22:19 UTC, jpa198 commented on cybershake/scenario_data.py
> +        help="Full file path to the summarise_all_rels_im script. Found in IM calculation",
"IM calculation" -> "the IM_calculation repository"

2021-09-13 22:19 UTC, jpa198 commented on cybershake/scenario_epsilon.py
> +                subprocess.Popen(shlex.split(f"{spatialise_im_ffp} {fault_im_filename} {config['station_file']} -o {xyz_output_dir}"))
Black this file too.
This line and 107 are causing the Black test to fail

2021-09-13 23:57 UTC, jasonmotha reviewed
Couple of spelling things. The rest are up for discussion - no strong feelings about my recommendations.

2021-09-13 23:57 UTC, jasonmotha commented on cybershake/scenario_data.py
> +Script for generating scenario data for a given model.
Is it easy to extend the im_calc script to accept multiple faults rather than having this wrapper script? I believe that's the only thing this script adds?

2021-09-13 23:57 UTC, jasonmotha commented on cybershake/scenario_epsilon.py
> +                subprocess.Popen(shlex.split(f"{plot_items_ffp} {plot_options} --xyz {non_uniform_im} -f {plot_output_filename} --xyz-cpt-labels {plot_output_filename} -c '{config['srfs'][fault]}' --
Rather than using split I think it's better to directly create a list of strings.

2021-09-13 23:57 UTC, jasonmotha commented on cybershake/scenario_im_fault.py
> +    )
Since this file is in the vis repo. I reckon you can grab it's location from __file__

2021-09-13 23:57 UTC, jasonmotha commented on cybershake/scenario_ratios.py
> +        description="Script for generating scenario ratio plots as ima nd sigma ratios between different models. The script will compare each model found in the scenario data directory and generate a
"as ima nd s" - > "as im and sigma"*

I've seen it twice. Might be worth a find and relpce.

2021-09-14 00:07 UTC, joelridden commented on cybershake/scenario_data.py
> +Script for generating scenario data for a given model.
Personally I liked keeping all the scenario stuff together. But you are right it is a rather small thing this script does and this also could be useful for other things other than scenario data to have the faults optional in the im_calc script. I'll make these adjustments.

2021-09-14 01:49 UTC, jasonmotha reviewed
Looks good! Nice turnaround.

2021-09-14 01:49 UTC, jasonmotha commented on cybershake/README.md
> +Data for scenarios is generated by running the **summarise_all_rels_im.py** script foudn in the IM_calculation repository.
found*

2021-09-14 01:49 UTC, jasonmotha commented on cybershake/scenario_epsilon.py
> +                    cpt_inc,
Just double checking that this is working as is. It might be limited to only strings working?

2021-09-14 01:49 UTC, jasonmotha commented on cybershake/scenario_ratios.py
> +        description="Script for generating scenario ratio plots as IM and sigma ratios between different models. The script will compare each model found in the scenario data directory and generate a
I'm not a fan of having this string duplicated thinking about it.

Though, is it okay to save the top docstring to a variable and use it here? It feels a little  hacky but better than having copy/paste?

2021-09-14 01:57 UTC, jpa198 requested changes

2021-09-14 01:57 UTC, jpa198 commented on cybershake/scenario_epsilon.py
> +        "-config_ffp",
Full word arguments should have double dash, only single letter shortcuts should use single dash. 
I assumed using single dash would automagically allow double dash to work, but my test script didn't do that

2021-09-14 01:58 UTC, jpa198 commented on cybershake/scenario_ratios.py
> +        description="Script for generating scenario ratio plots as IM and sigma ratios between different models. The script will compare each model found in the scenario data directory and generate a
Apparently it's the __doc__ variable: 
https://stackoverflow.com/questions/7791574/how-can-i-print-a-python-files-docstring-when-executing-it

2021-09-14 02:00 UTC, joelridden commented on cybershake/scenario_ratios.py
> +        description="Script for generating scenario ratio plots as IM and sigma ratios between different models. The script will compare each model found in the scenario data directory and generate a
Indeed that does work, will use this!

2021-09-14 02:01 UTC, jasonmotha commented on cybershake/scenario_ratios.py
> +        description="Script for generating scenario ratio plots as IM and sigma ratios between different models. The script will compare each model found in the scenario data directory and generate a
That is magic.

2021-09-14 02:20 UTC, joelridden commented on cybershake/scenario_epsilon.py
> +                    cpt_inc,
Good point, they do need to be strings

2021-09-14 02:57 UTC, jasonmotha approved these changes

2021-09-15 00:04 UTC, claudio525 approved these changes

2021-09-15 00:04 UTC, claudio525 commented on cybershake/scenario_epsilon.py
> +    parser = argparse.ArgumentParser(description=__doc__)
Legit :+1:

2021-09-15 00:15 UTC, jpa198 approved these changes
Nice

2021-09-15 00:16 UTC, jpa198 commented on cybershake/scenario_ratios.py
> +                subprocess.Popen([str(im_ratios_ffp), str(file), str(file_pair), str(output_filename)])
Formatting for this line is the test fail

2021-09-15 00:26 UTC, joelridden commented on cybershake/scenario_ratios.py
> +                subprocess.Popen([str(im_ratios_ffp), str(file), str(file_pair), str(output_filename)])
Ah I think I forgot to black one of the files, simple fix

2021-09-15 00:31 UTC, merged