added option to disable roads/highways on the map plots
ucgmsim/visualization pull request #85
Opened 2022-08-18 23:19 UTC by jasonmotha

Just because plot_items needed more customisation.

2022-08-22 04:24 UTC, sungeunbae reviewed
So you want roads and highways by default when args.fast is True, but none of them otherwise? Seems a little counter-intuitive. Thoughts?

2022-08-22 22:10 UTC, jasonmotha commented
> So you want roads and highways by default when args.fast is True, but none of them otherwise? Seems a little counter-intuitive. Thoughts?

Good spotting. It's a bug - none of us use --fast though so we wouldn't have seen it but still a good find.

2022-09-22 23:49 UTC, jpa198 approved these changes

2022-09-22 23:59 UTC, sungeunbae requested changes

2022-09-22 23:59 UTC, sungeunbae commented on sources/plot_items.py
> +    roads = "auto" if args.enable_roads and not args.fast else None
I think it is simpler to change the logic to 
`roads = "auto" if args.enable_roads  else None`
then `road=None, highway=None`  in `if args.fast` block below

2022-09-23 00:04 UTC, sungeunbae approved these changes

2022-09-23 00:05 UTC, merged